
import { Track } from './SoundCloudPlayerContext';
import Lukeokagha from '../public/Lukeokagha.jpg';

export const initialTracks: Track[] = [
  {
    id: 'lukeintro',
    title: 'Luke Intro Music',
    url: '/lukeintro.mp3',
    artwork_url: Lukeokagha.src,
    type: 'local',
    loaded: false,
  },
  {
    id: 'black-lips-poem-playlist',
    title: 'Black Lips Poem',
    url: 'https://api.soundcloud.com/playlists/soundcloud:playlists:1073911384',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'suffering-and-smiling',
    title: 'Suffering and Smiling',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:841919407',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'airplane-mood',
    title: 'Airplane Mood',
    url: 'https://soundcloud.com/lukewealth/airplane-mood',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'hey-i-know-a-place',
    title: 'HEY! I KNOW A PLACE',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:338201763',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'use-ya-head',
    title: 'Use Ya Head',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:368936195',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'total-freedom',
    title: 'Total Freedom',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:841916449',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: '2019-election',
    title: '2019 Election',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:841922392',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'a-royal-gift',
    title: 'A ROYAL GIFT',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:311072059',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'mathematical-law-of-love',
    title: 'Mathematical Law Of Lov3',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:304885464',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'dont-you-worry-child',
    title: "Don't You Worry Child (Ibo Cover)",
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:290600205',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'i-worship',
    title: 'i worship ft H.O.S(DAREAL N JUSTIN VERZ)',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:289881813',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'truth-in-lies',
    title: 'Truth iN LIES',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:311072715',
    type: 'soundcloud',
    loaded: false,
  },
  {
    id: 'human-being',
    title: 'Human Being',
    url: 'https://api.soundcloud.com/tracks/soundcloud:tracks:304889757',
    type: 'soundcloud',
    loaded: false,
  },
];
